import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "@/lib/ReactQueryProvider";
import { Toaster } from 'sonner';
import NextTopLoader from 'nextjs-toploader';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const lora = localFont({
  src: "./fonts/Lora-VariableFont_wght.woff",
  variable: "--font-lora",
  weight: "400 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} antialiased`}
      >
        <ReactQueryProvider>
          <NextTopLoader color="#000000" height={3} showSpinner={false}/>
          {children}
          <Toaster position="top-center" richColors={true} />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
